### ISSUE TITLE
No Toolbars after Chrome update

### ISSUE THREAD

**Issue by patriclougheed** [duopixel/Method-Draw#52] opened 2016-02-22 21:21 UTC
Was working great until the latest Chrome update and now no menus or toolbars. Works fine in Firefox.

![2016-02-22 13_14_33-method draw](https://cloud.githubusercontent.com/assets/1463351/13233146/2e6c81fc-d967-11e5-9e08-8fc3885f8460.jpg)

Uncaught TypeError: oa.createSVGPathSegLinetoAbs is not a function(anonymous function) @ method-draw.compiled.js:64

(anonymous function) @ method-draw.compiled.js:64(anonymous function) @ method-draw.compiled.js:70

lstr.js:26 Uncaught TypeError: Cannot read property 'appendChild' of undefined(anonymous function) @ lstr.js:26

**Comment by duopixel** [comment] 2016-02-22 21:53
Upgrade to the latest version of Method Draw, bug report dupe of https://github.com/duopixel/Method-Draw/issues/44

You can see it working with the latest version of Chrome at http://editor.method.ac

**Closed by duopixel** 2016-02-22 21:53 UTC
